#!/bin/bash

clear

# Declaring Variables
language=-1
lastMessage="?"

# Loop to select the correct language
while [[ $language =~ ^-[0-9]+$ ]]
do
    read -r -p "================================
- Select your language:

0 - English ( United States )
1 - Portuguese ( Brasil )
2 - French ( Canada )
3 - Spanish ( Spain )
4 - Japanese ( Japan )
================================
Your choice: " language
done

echo "
Commands: 
    -q to quit from saymode
    -r to restart the saymode
    -l to say the last message
================================
Say: 
"

# Varable to define language - By default = language computer
voice=""

if [[ $language == 0 ]] 
# English - United States
then 
    voice="-v Alex"
elif [[ $language == 1 ]] 
# Brazil - Portuguese
then 
    voice="-v Luciana"
elif [[ $language == 2 ]] 
# French - Canada
then 
    voice="-v Amelie"
elif [[ $language == 3 ]] 
# Spanish - Spain
then 
    voice="-v Monica"
elif [[ $language == 4 ]] 
# Japanese - Japan
then 
    voice="-v Kyoko"
fi

# Infinity loop
while true
do
    read -r input
    
    #Comands
    if [[ "$input" == "-r" ]]
    then
        exec bash "$0" "$@"
    elif [[ "$input" == "-q" ]]
    then
        exit
    elif [[ "$input" == "-l" ]]
    then
        say $voice $lastMessage
    else
        lastMessage="$input"
        say $voice $input
    fi
done
