#!/bin/bash

clear

# Declaring Variables
language=-1
lastMessage="?"

# Loop to select the correct language
while [[ $language =~ ^-[0-9]+$ ]]
do
    read -r -p "================================
- Select your language:

0 - Default
1 - Portuguese ( Brasil )
================================
Your choice: " language
done

echo "
Commands: 
    -exit to stop the saymode
    -restart to restart the saymode
    -l to say the last message
================================
Say: 
"

# Varable to define language - By default = language computer
voice=""

if [[ $language == 1 ]] 
# Brazil - Portuguese
then 
    voice="-v Luciana"
fi

# Infinity loop
while true
do
    read -r input
    
    #Comands
    if [[ "$input" == "-restart" ]]
    then
        exec bash "$0" "$@"
    elif [[ "$input" == "-exit" ]]
    then
        exit
    elif [[ "$input" == "-l" ]]
    then
        say $voice $lastMessage
    else
        lastMessage="$input"
        say $voice $input
    fi
done
